image: jdubois/jhipster-docker:latest

before_script:
  - npm install phantomjs

stages:
  - build
  - test
  - deploy

<%_ if (buildTool == 'maven') { _%>
maven-test:
  stage: test
  script: "mvn test"
<%_ } _%>
<%_ if (buildTool == 'gradle') { _%>
gradle-test:
  stage: test
  script: "./gradlew test"
<%_ } _%>

<%_ if (frontendBuilder == 'grunt') { _%>
grunt-test:
  stage: test
  script: "grunt test"
<%_ } _%>
<%_ if (frontendBuilder == 'gulp') { _%>
gulp-test:
  stage: test
  script: "gulp test"
<%_ } _%>
