image: moifort/jhipster-gitlab-ci-image:2.26.1-cache

before_script:
  - cp -r /root/node_modules .
  - npm install

stages:
  - build
  - test
  - deploy

<%_ if (buildTool == 'maven') { _%>
maven-test:
  stage: test
  script: "mvn test"
<%_ } _%>
<%_ if (buildTool == 'gradle') { _%>
gradle-test:
  stage: test
  script: "./gradlew test --no-daemon"
<%_ } _%>

<%_ if (frontendBuilder == 'grunt') { _%>
grunt-test:
  stage: test
  script: "grunt test"
<%_ } _%>
<%_ if (frontendBuilder == 'gulp') { _%>
gulp-test:
  stage: test
  script: "gulp test"
<%_ } _%>
