os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install:
  - npm install -g bower gulp
install:
  - npm install
  - bower install
script:
<%_ if (buildTool == 'maven') { _%>
  - mvn test
<%_ } _%>
<%_ if (buildTool == 'gradle') { _%>
  - ./gradlew test --no-daemon
<%_ } _%>
  - gulp test
