os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install:
  - npm install -g bower
<%_ if (frontendBuilder == 'grunt') { _%>
  - npm install -g grunt-cli
<%_ } _%>
<%_ if (frontendBuilder == 'gulp') { _%>
  - npm install -g gulp
<%_ } _%>
install:
  - npm install
  - bower install
script:
<%_ if (buildTool == 'maven') { _%>
  - mvn test
<%_ } _%>
<%_ if (buildTool == 'gradle') { _%>
  - ./gradlew test
<%_ } _%>
  - gulp test
